/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author Valeria
 */
public class frmReportes extends javax.swing.JFrame {

    /**
     * Creates new form frmReportes
     */
    public frmReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplMenuReportes = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnEstudiantes = new javax.swing.JButton();
        btnLabComputo = new javax.swing.JButton();
        btnBloqueos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reportes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplMenuReportes.setBackground(new java.awt.Color(236, 236, 236));
        jplMenuReportes.setToolTipText("");
        jplMenuReportes.setName(""); // NOI18N
        jplMenuReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitulo.setText("Generar reporte");
        jplMenuReportes.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 180, -1));

        btnEstudiantes.setBackground(new java.awt.Color(102, 204, 255));
        btnEstudiantes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEstudiantes.setText("Reporte de Carreras");
        btnEstudiantes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantesActionPerformed(evt);
            }
        });
        jplMenuReportes.add(btnEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 230, 50));

        btnLabComputo.setBackground(new java.awt.Color(102, 204, 255));
        btnLabComputo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnLabComputo.setText("Reporte de centro de computo");
        btnLabComputo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnLabComputo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabComputoActionPerformed(evt);
            }
        });
        jplMenuReportes.add(btnLabComputo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 230, 50));

        btnBloqueos.setBackground(new java.awt.Color(102, 204, 255));
        btnBloqueos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnBloqueos.setText("Reporte de Bloqueos");
        btnBloqueos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnBloqueos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloqueosActionPerformed(evt);
            }
        });
        jplMenuReportes.add(btnBloqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 230, 50));

        getContentPane().add(jplMenuReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantesActionPerformed
        frmCatalogoEstudiantes ir = new frmCatalogoEstudiantes();
        ir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEstudiantesActionPerformed

    private void btnLabComputoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabComputoActionPerformed
        frmCatalogoLaboratorio ir = new frmCatalogoLaboratorio();
        ir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLabComputoActionPerformed

    private void btnBloqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloqueosActionPerformed
        frmCatalogoBloqueos ir = new frmCatalogoBloqueos();
        ir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBloqueosActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmReportes().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBloqueos;
    private javax.swing.JButton btnEstudiantes;
    private javax.swing.JButton btnLabComputo;
    private javax.swing.JPanel jplMenuReportes;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
