/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author cesar
 */
public class frmConfirmacion extends javax.swing.JFrame {

    /**
     * Creates new form frmConfirmacion
     */
    public frmConfirmacion() {
       initComponents();
        setSize(603, 500); 
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblNumeroTitul = new javax.swing.JLabel();
        lblPC = new javax.swing.JLabel();
        btnConfirmrSeleccion = new javax.swing.JButton();
        btnSoftware = new javax.swing.JButton();
        lblText = new javax.swing.JLabel();
        lblTextt = new javax.swing.JLabel();
        lblNumPC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Computadora seleccionada");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logotipoazul.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 60));

        lblNumeroTitul.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumeroTitul.setText("Numero:");
        jPanel1.add(lblNumeroTitul, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 100, 30));

        lblPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/compuITson.png"))); // NOI18N
        jPanel1.add(lblPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        btnConfirmrSeleccion.setBackground(new java.awt.Color(51, 153, 255));
        btnConfirmrSeleccion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnConfirmrSeleccion.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmrSeleccion.setText("Confirmar Seleccion");
        btnConfirmrSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmrSeleccionActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmrSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        btnSoftware.setBackground(new java.awt.Color(51, 153, 255));
        btnSoftware.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSoftware.setForeground(new java.awt.Color(255, 255, 255));
        btnSoftware.setText("Software");
        btnSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoftwareActionPerformed(evt);
            }
        });
        jPanel1.add(btnSoftware, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, 40));

        lblText.setText("Para ver el software que tiene esta PC ");
        jPanel1.add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        lblTextt.setText("da click aqui");
        jPanel1.add(lblTextt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        lblNumPC.setText("Numero PC");
        jPanel1.add(lblNumPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoftwareActionPerformed
      frmSoftwareVista sf=new frmSoftwareVista();
      sf.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnSoftwareActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
       frmSeleccionPC sel=new frmSeleccionPC();
       sel.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnConfirmrSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmrSeleccionActionPerformed
      frmApartadaExito ex=new frmApartadaExito();
      ex.setVisible(true);
      this.dispose();
      
    }//GEN-LAST:event_btnConfirmrSeleccionActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmrSeleccion;
    private javax.swing.JButton btnSoftware;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNumPC;
    private javax.swing.JLabel lblNumeroTitul;
    private javax.swing.JLabel lblPC;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblTextt;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
