/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import BO.AdministradorBO;
import javax.swing.JOptionPane;

/**
 *
 * @author Valeria
 */
public class frmInicioSesionAdminsitrador extends javax.swing.JFrame {

    private AdministradorBO administradorBO;

    /**
     * Creates new form frmInicioSesionAdminsitrador
     */
    public frmInicioSesionAdminsitrador() {
        administradorBO = new AdministradorBO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplInicioSesionAdm = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio Sesión Administrador");
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplInicioSesionAdm.setBackground(new java.awt.Color(236, 236, 236));
        jplInicioSesionAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitulo.setText("INICIO SESIÓN ADMINISTADOR");
        jplInicioSesionAdm.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 340, 30));
        jplInicioSesionAdm.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 260, 30));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuario.setText("Usuario");
        jplInicioSesionAdm.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblContraseña.setText("Contraseña");
        jplInicioSesionAdm.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        jplInicioSesionAdm.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 260, 30));

        btnIniciarSesion.setBackground(new java.awt.Color(102, 204, 255));
        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Ingresar");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        jplInicioSesionAdm.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logotipooogri.png"))); // NOI18N
        jplInicioSesionAdm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 290, 100));

        getContentPane().add(jplInicioSesionAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // Obtén los datos de usuario y contraseña ingresados
        String usuario = txtUsuario.getText();
        String contraseña = new String(txtContraseña.getPassword());

        // Verifica si los campos están vacíos
        if (usuario.isEmpty() || contraseña.isEmpty()) {
            // Muestra un mensaje si algún campo está vacío
            JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return; // Detiene el flujo para que no continúe si hay campos vacíos
        }

        // Llama a la capa de negocio para validar el administrador
        boolean esValido = administradorBO.validarCredenciales(usuario, contraseña);

        // Si las credenciales son correctas, abrir la siguiente ventana
        if (esValido) {
            frmMenuAdministrador ir = new frmMenuAdministrador();
            ir.setVisible(true);
            this.dispose();
        } else {
            // Si las credenciales son incorrectas, muestra un mensaje de error
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicioSesionAdminsitrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicioSesionAdminsitrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicioSesionAdminsitrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicioSesionAdminsitrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicioSesionAdminsitrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jplInicioSesionAdm;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
