package presentacion;

/**
 *
 * @author Valeria
 */
public class frmMenuAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuAdministrador
     */
    public frmMenuAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuAdm = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btbReportes = new javax.swing.JButton();
        btnEstudiantes = new javax.swing.JButton();
        btnLabComputo = new javax.swing.JButton();
        btnBloqueos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Adminstrador");
        setPreferredSize(new java.awt.Dimension(630, 490));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenuAdm.setBackground(new java.awt.Color(236, 236, 236));
        pnlMenuAdm.setToolTipText("");
        pnlMenuAdm.setName(""); // NOI18N
        pnlMenuAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitulo.setText("Seleccione que desea administrar");
        pnlMenuAdm.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 350, -1));

        btbReportes.setBackground(new java.awt.Color(102, 204, 255));
        btbReportes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btbReportes.setText("Reportes");
        btbReportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btbReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbReportesActionPerformed(evt);
            }
        });
        pnlMenuAdm.add(btbReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 200, 50));

        btnEstudiantes.setBackground(new java.awt.Color(102, 204, 255));
        btnEstudiantes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEstudiantes.setText("Estudiantes");
        btnEstudiantes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantesActionPerformed(evt);
            }
        });
        pnlMenuAdm.add(btnEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 200, 50));

        btnLabComputo.setBackground(new java.awt.Color(102, 204, 255));
        btnLabComputo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnLabComputo.setText("Laboratorio Computo");
        btnLabComputo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnLabComputo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabComputoActionPerformed(evt);
            }
        });
        pnlMenuAdm.add(btnLabComputo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 200, 50));

        btnBloqueos.setBackground(new java.awt.Color(102, 204, 255));
        btnBloqueos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnBloqueos.setText("Bloqueos");
        btnBloqueos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnBloqueos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloqueosActionPerformed(evt);
            }
        });
        pnlMenuAdm.add(btnBloqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 200, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logotipooogri.png"))); // NOI18N
        pnlMenuAdm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 310, 120));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cerrar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlMenuAdm.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 110, 30));

        getContentPane().add(pnlMenuAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLabComputoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabComputoActionPerformed
        frmCatalogoLaboratorio ir = new frmCatalogoLaboratorio();
        ir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLabComputoActionPerformed

    private void btnEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantesActionPerformed
        frmCatalogoEstudiantes ir = new frmCatalogoEstudiantes();
        ir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEstudiantesActionPerformed

    private void btnBloqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloqueosActionPerformed
        frmCatalogoBloqueos ir = new frmCatalogoBloqueos();
        ir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBloqueosActionPerformed

    private void btbReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbReportesActionPerformed
        frmMenuReportes ir = new frmMenuReportes();
        ir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btbReportesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    frmInicioSesionAdminsitrador ad=new frmInicioSesionAdminsitrador();
    ad.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbReportes;
    private javax.swing.JButton btnBloqueos;
    private javax.swing.JButton btnEstudiantes;
    private javax.swing.JButton btnLabComputo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlMenuAdm;
    // End of variables declaration//GEN-END:variables
}
