/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author Valeria
 */
public class frmPdfReporteBloqueo extends javax.swing.JFrame {

    /**
     * Creates new form frmPdfReporteBloqueo
     */
    public frmPdfReporteBloqueo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRepBloqueos = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnDescargar = new javax.swing.JButton();
        splRepBloqueos = new javax.swing.JScrollPane();
        tblTablaRepBloqueos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRepBloqueos.setBackground(new java.awt.Color(255, 255, 255));
        pnlRepBloqueos.setToolTipText("Reporte de Carreras");
        pnlRepBloqueos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(204, 0, 0));
        txtTitulo.setText("Reporte de Bloqueos");
        pnlRepBloqueos.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        btnSalir.setBackground(new java.awt.Color(204, 0, 0));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlRepBloqueos.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, 130, 30));

        btnDescargar.setBackground(new java.awt.Color(204, 0, 0));
        btnDescargar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDescargar.setForeground(new java.awt.Color(255, 255, 255));
        btnDescargar.setText("Descargar");
        pnlRepBloqueos.add(btnDescargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 130, 30));

        tblTablaRepBloqueos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombredel alumno ", " Fecha de bloqueo", " Fecha de liberación", "Motivo"
            }
        ));
        splRepBloqueos.setViewportView(tblTablaRepBloqueos);

        pnlRepBloqueos.add(splRepBloqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 530, 350));

        getContentPane().add(pnlRepBloqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        frmMenuAdministrador salir = new frmMenuAdministrador();
        salir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmPdfReporteBloqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmPdfReporteBloqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmPdfReporteBloqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmPdfReporteBloqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmPdfReporteBloqueo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescargar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel pnlRepBloqueos;
    private javax.swing.JScrollPane splRepBloqueos;
    private javax.swing.JTable tblTablaRepBloqueos;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
