package presentacion;

/**
 *
 * @author Valeria
 */
public class frmReporteBloqueos extends javax.swing.JFrame {

    /**
     * Creates new form frmReporteBloqueos
     */
    public frmReporteBloqueos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRepBloqueos = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        dtcFechaInicio = new com.toedter.calendar.JDateChooser();
        dtcFechaFin = new com.toedter.calendar.JDateChooser();
        splRepBloqueos = new javax.swing.JScrollPane();
        tblTablaRepBloqueos = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        btnVistaPrevia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reporte de Bloqueos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRepBloqueos.setBackground(new java.awt.Color(255, 255, 255));
        pnlRepBloqueos.setToolTipText("Reporte de Carreras");
        pnlRepBloqueos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(204, 0, 0));
        txtTitulo.setText("Reporte de Bloqueos");
        pnlRepBloqueos.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        lblFechaInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFechaInicio.setText("Fecha Inicio:");
        pnlRepBloqueos.add(lblFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 30));

        lblFechaFin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFechaFin.setText("Fecha Fin:");
        pnlRepBloqueos.add(lblFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, 30));

        dtcFechaInicio.setBackground(new java.awt.Color(255, 255, 255));
        pnlRepBloqueos.add(dtcFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 120, 25));

        dtcFechaFin.setBackground(new java.awt.Color(255, 255, 255));
        pnlRepBloqueos.add(dtcFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 25));

        tblTablaRepBloqueos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombredel alumno ", " Fecha de bloqueo", " Fecha de liberación", "Motivo"
            }
        ));
        splRepBloqueos.setViewportView(tblTablaRepBloqueos);

        pnlRepBloqueos.add(splRepBloqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 530, 250));

        btnConsultar.setBackground(new java.awt.Color(102, 204, 255));
        btnConsultar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        pnlRepBloqueos.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 130, 40));

        btnVistaPrevia.setText("Vista Previa");
        pnlRepBloqueos.add(btnVistaPrevia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        getContentPane().add(pnlRepBloqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        frmPdfReporteBloqueo consultar = new frmPdfReporteBloqueo();
        consultar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmReporteBloqueos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmReporteBloqueos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmReporteBloqueos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmReporteBloqueos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmReporteBloqueos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnVistaPrevia;
    private com.toedter.calendar.JDateChooser dtcFechaFin;
    private com.toedter.calendar.JDateChooser dtcFechaInicio;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JPanel pnlRepBloqueos;
    private javax.swing.JScrollPane splRepBloqueos;
    private javax.swing.JTable tblTablaRepBloqueos;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
